In [2]:
import tensorflow as tf
import numpy as np
import os
import time
import cv2
import numpy as np
from tqdm import tqdm

In [3]:
112

112

In [5]:
def load_graph(frozen_graph_filename):
    # We load the protobuf file from the disk and parse it to retrieve the 
    # unserialized graph_def
    with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())

    # Then, we can use again a convenient built-in function to import a graph_def into the 
    # current default Graph
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(
            graph_def, 
            input_map=None, 
            return_elements=None, 
            name="prefix", 
            op_dict=None, 
            producer_op_list=None
        )

    input_name = graph.get_operations()[0].name+':0'
    output_name = graph.get_operations()[-1].name+':0'
    return graph, input_name, output_name

In [6]:
model_path = "/home/junior/Documents/seguidor_linha/modelo_9935.pb"
load_graph(model_path)

W1010 23:39:32.316612 140284579424064 deprecation.py:506] From <ipython-input-5-2055476cfb0e>:17: calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.
Instructions for updating:
Please file an issue at https://github.com/tensorflow/tensorflow/issues if you depend on this feature.


(<tensorflow.python.framework.ops.Graph at 0x7f963cee0400>,
 'prefix/conv2d_1_input:0',
 'prefix/dense_3/Softmax:0')

In [7]:
resultado = []
def prepare_data_x(img_dir,label=False,invert_color=False):
    inicio = time.time()
    tipos = ['cruzamento', 'curva', 'parada', 'reta', 'zigzag']
    aux = []
#     resultado = []

#     print(img_dir)
    frame = cv2.imread(img_dir,0)
    img = frame
#     img = cv2.resize(frame, (150,150))
    if invert_color:
        img = (255-img)
    aux.append(img)
    img = np.array(aux)
    img = img/255
    img = img.reshape(img.shape[0], img.shape[1], img.shape[2], 1).astype('float32')
#     print("tempo antes pred:",time.time()-inicio)
#     resultado.append(img)
#     return np.array(resultado)
    return img
#     pred = model.predict(img)
#     print("tempo pos pred:",time.time()-inicio)
#     pred = np.around(pred, decimals = 2, out = None) 
#     print("tempo TOTAL:",time.time()-inicio)
#     return tipos[np.argmax(pred)],pred,frame

In [8]:
prepare_data_x("teste.jpg").shape

(1, 480, 640, 1)

In [9]:
tipos = ['cruzamento', 'curva', 'parada', 'reta', 'zigzag']
def predict(model_path,folder):
    # load tf graph
    tf_model,tf_input,tf_output = load_graph(model_path)
    # Create tensors for model input and output
    x = tf_model.get_tensor_by_name(tf_input)
    y = tf_model.get_tensor_by_name(tf_output) 
    num_outputs = y.shape.as_list()[0]
    
    fotos = (os.listdir(folder))
    predictions = np.zeros((len(fotos),len(tipos)))
    
    with tf.Session(graph=tf_model) as sess:
        for foto in tqdm(fotos):    
            tempo1 = time.time()
            y_out = sess.run(y, feed_dict={x: prepare_data_x(folder+foto)})
            print("tempo pred:",time.time()-tempo1)
            predictions = y_out[0]
            print(predictions)
            pred = np.around(predictions, decimals = 2, out = None) 
            print (pred)
            print(tipos[np.argmax(pred)])
        #     return tipos[np.argmax(pred)],pred,input_data
#     return predictions

In [24]:
predict(model_path,"/home/junior/Downloads/separado/curva/")

  4%|▍         | 10/250 [00:00<00:57,  4.20it/s]

tempo pred: 0.33472704887390137
[1.6718151e-12 1.0000000e+00 1.4789081e-11 3.1597602e-10 5.4868932e-11]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.01101231575012207
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010427236557006836
[2.8667737e-17 1.0000000e+00 5.1778379e-20 1.1129665e-15 3.4006287e-16]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.011155366897583008
[2.8635145e-26 1.0000000e+00 4.5141668e-31 8.8871387e-29 3.0972395e-17]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009916067123413086
[1.3028483e-38 1.0000000e+00 0.0000000e+00 3.8930638e-36 2.2888010e-33]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010004043579101562
[4.3608696e-30 1.0000000e+00 6.8200107e-37 1.4632023e-36 2.1434356e-21]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010399818420410156
[5.4270778e-33 1.0000000e+00 2.2571391e-38 2.5904654e-26 9.8233990e-30]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.011013031005859375
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009969711303710938
[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+0

 12%|█▏        | 30/250 [00:00<00:26,  8.17it/s]

tempo pred: 0.01040339469909668
[1.2107825e-34 1.0000000e+00 0.0000000e+00 2.4547489e-32 4.5464978e-25]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.011389732360839844
[2.0337296e-26 1.0000000e+00 4.4461146e-31 4.9348216e-24 8.6212222e-25]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009926557540893555
[2.8217488e-31 1.0000000e+00 0.0000000e+00 3.2691535e-32 4.1942136e-27]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010209798812866211
[7.3326518e-28 1.0000000e+00 5.1171402e-36 2.2414238e-27 4.7862420e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.00960850715637207
[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 2.7810891e-37]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010468721389770508
[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 1.0732317e-31]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010045528411865234
[8.1856827e-11 1.0000000e+00 3.4030493e-12 3.2197683e-08 6.6114703e-10]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.00998544692993164
[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 4.0161524e-36]
[0

 20%|██        | 50/250 [00:00<00:13, 15.29it/s]

tempo pred: 0.009054422378540039
[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 6.0136414e-35]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010395526885986328
[2.3514869e-25 1.0000000e+00 3.8611335e-28 1.7081112e-24 3.0786410e-16]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010605335235595703
[5.8684212e-28 1.0000000e+00 4.3481654e-36 2.5943114e-27 3.9204348e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009513139724731445
[3.0341710e-25 1.0000000e+00 7.3752496e-32 1.0189602e-24 9.1137187e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010693073272705078
[5.3534593e-28 1.0000000e+00 1.4325464e-33 9.9600136e-26 1.1499581e-21]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010132551193237305
[4.0332819e-31 1.0000000e+00 2.9488830e-34 1.4210592e-22 3.7741121e-26]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010137319564819336
[1.8355125e-28 1.0000000e+00 5.6551208e-33 4.7669858e-30 8.3142087e-22]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010596513748168945
[7.8553578e-14 1.0000000e+00 9.7884856e-10 3.2728945e-11 3.8710334e-11]

 28%|██▊       | 70/250 [00:01<00:06, 26.57it/s]

tempo pred: 0.009385347366333008
[1.7146290e-36 1.0000000e+00 0.0000000e+00 1.0233418e-33 8.1398225e-28]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009153366088867188
[1.040781e-28 1.000000e+00 1.004735e-35 1.721389e-25 2.173789e-27]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010042190551757812
[0.0000000e+00 1.0000000e+00 0.0000000e+00 9.1641720e-30 6.2139335e-29]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010902643203735352
[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.1688473e-36 0.0000000e+00]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.00926661491394043
[2.8648113e-16 9.9999368e-01 9.0203080e-17 1.3345492e-17 6.2650993e-06]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010910987854003906
[2.1479915e-24 1.0000000e+00 2.4076604e-28 6.3399486e-22 1.2805301e-19]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009403228759765625
[2.1277881e-19 1.0000000e+00 3.3040095e-23 4.4603357e-15 6.7629583e-16]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009994029998779297
[1.4909637e-28 1.0000000e+00 5.0704449e-37 1.8217147e-28 1.2551847e-24]
[0. 1

 36%|███▌      | 89/250 [00:01<00:03, 41.72it/s]

tempo pred: 0.008968114852905273
[1.8310274e-38 1.0000000e+00 0.0000000e+00 0.0000000e+00 4.2045493e-33]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010411262512207031
[6.0728356e-37 1.0000000e+00 7.1097963e-26 4.8783944e-37 6.0327796e-28]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009424686431884766
[5.43940273e-13 9.99999881e-01 6.18211871e-11 1.16478056e-07
 2.10560069e-10]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009251832962036133
[2.9559989e-28 1.0000000e+00 2.9534215e-33 6.5696570e-30 4.2794545e-25]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.011220455169677734
[3.7265507e-30 1.0000000e+00 9.0279977e-34 4.0640567e-26 1.8088679e-22]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010946035385131836
[1.5326374e-31 1.0000000e+00 0.0000000e+00 1.0107528e-32 5.5544386e-27]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010464191436767578
[1.6722989e-28 1.0000000e+00 3.8471042e-37 9.6736512e-29 1.2507920e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.01022791862487793
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009184837341

 44%|████▎     | 109/250 [00:01<00:02, 58.27it/s]

tempo pred: 0.010286092758178711
[2.0745985e-21 1.0000000e+00 3.8890335e-25 6.2318407e-19 1.4976586e-17]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009505271911621094
[1.5197644e-07 9.9999595e-01 7.3788800e-07 2.0282628e-06 1.1708216e-06]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009198188781738281
[9.1368189e-27 1.0000000e+00 1.2494809e-31 1.1558276e-24 2.7912882e-25]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010367155075073242
[1.0674787e-12 1.0000000e+00 1.1737787e-16 4.2181831e-13 4.2954299e-12]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009762048721313477
[7.240070e-07 9.998247e-01 4.034857e-06 1.616388e-04 8.934662e-06]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010050296783447266
[2.7844493e-33 1.0000000e+00 0.0000000e+00 3.9778771e-31 1.3123986e-26]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010779857635498047
[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 2.0599787e-35]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009017467498779297
[6.4504853e-29 1.0000000e+00 1.1518014e-37 5.8633390e-29 5.7943554e-25]
[0. 

 52%|█████▏    | 129/250 [00:01<00:01, 72.18it/s]


curva
tempo pred: 0.010468482971191406
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.008990287780761719
[6.2927565e-09 9.9993777e-01 9.0801855e-09 6.1968756e-05 2.2966870e-07]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010154962539672852
[9.7501620e-35 1.0000000e+00 0.0000000e+00 2.0795981e-36 7.3549722e-30]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010131597518920898
[1.1523300e-20 1.0000000e+00 8.8279877e-26 1.4531151e-17 3.2149396e-15]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009138107299804688
[1.9589477e-18 1.0000000e+00 9.8811562e-13 1.4404743e-20 2.4421416e-08]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010733842849731445
[6.5621140e-31 1.0000000e+00 3.9468988e-27 6.1955934e-28 1.6827531e-23]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010016918182373047
[0.0000000e+00 1.0000000e+00 0.0000000e+00 2.9535053e-37 8.9959871e-35]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010271787643432617
[2.9310205e-17 1.0000000e+00 1.1295609e-17 1.2219030e-14 2.2741054e-11]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.0101907253

 60%|█████▉    | 149/250 [00:01<00:01, 81.67it/s]

tempo pred: 0.01022648811340332
[6.526018e-38 1.000000e+00 0.000000e+00 0.000000e+00 1.823252e-27]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009490728378295898
[1.2284267e-15 1.0000000e+00 5.1665887e-21 2.0589361e-18 6.4256491e-16]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010525703430175781
[1.6066158e-20 1.0000000e+00 3.2835703e-36 9.7791324e-37 5.0346087e-17]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009160041809082031
[1.8967595e-25 1.0000000e+00 5.5418977e-31 1.7633304e-21 7.0226307e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009981393814086914
[4.3555883e-35 1.0000000e+00 0.0000000e+00 6.7489431e-37 2.9558266e-30]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009035110473632812
[2.8408982e-16 1.0000000e+00 1.3620446e-22 9.4156011e-20 3.8466592e-17]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009891748428344727
[3.1310321e-27 1.0000000e+00 0.0000000e+00 8.1726860e-34 2.9226454e-18]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010462284088134766
[6.8098564e-34 1.0000000e+00 0.0000000e+00 6.2398000e-37 6.7488025e-33]
[0. 1

 68%|██████▊   | 169/250 [00:02<00:00, 86.85it/s]

tempo pred: 0.010173320770263672
[1.7730180e-34 1.0000000e+00 0.0000000e+00 8.8724486e-34 1.4102153e-30]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009323596954345703
[2.4896978e-14 1.0000000e+00 2.8945027e-14 1.2895675e-11 1.2202553e-12]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010792255401611328
[5.6249638e-23 1.0000000e+00 2.1352621e-25 9.5860320e-23 6.4441115e-15]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.01013040542602539
[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 1.1451559e-36]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010090351104736328
[1.5604385e-27 1.0000000e+00 1.7701719e-35 7.1127220e-27 9.7050197e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010336875915527344
[1.0287112e-19 1.0000000e+00 3.6024785e-26 1.8407630e-22 1.9879217e-19]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009968042373657227
[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 2.7944582e-36]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010746479034423828
[2.8024276e-32 1.0000000e+00 6.5669589e-35 9.8305132e-24 2.7866631e-23]


 76%|███████▌  | 189/250 [00:02<00:00, 90.76it/s]

tempo pred: 0.009897470474243164
[6.0554258e-19 1.0000000e+00 9.9933945e-25 1.4228127e-20 2.5575812e-19]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010383844375610352
[4.8588974e-28 1.0000000e+00 2.3485423e-36 1.4583665e-27 2.7253920e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.00932931900024414
[1.0618275e-27 1.0000000e+00 6.4910670e-36 2.5026267e-27 5.9172808e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.01042318344116211
[1.0509938e-37 1.0000000e+00 0.0000000e+00 0.0000000e+00 2.9541365e-37]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.011320829391479492
[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 2.9684115e-32]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009100914001464844
[9.3531661e-28 1.0000000e+00 7.0137531e-36 3.2194361e-27 5.4692717e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009248733520507812
[2.7554584e-38 1.0000000e+00 0.0000000e+00 0.0000000e+00 1.9191509e-36]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010068893432617188
[2.0518829e-22 1.0000000e+00 1.5031505e-28 1.3744208e-20 6.1095018e-22]
[

 84%|████████▎ | 209/250 [00:02<00:00, 92.03it/s]

tempo pred: 0.009359598159790039
[3.1302386e-23 1.0000000e+00 1.4226672e-26 4.8991798e-18 4.1319762e-20]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.00990605354309082
[1.7857382e-19 1.0000000e+00 9.2662630e-21 2.5178491e-22 2.5990435e-10]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.00903177261352539
[2.8718489e-27 1.0000000e+00 4.6444808e-36 3.3452422e-29 1.3318930e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010234355926513672
[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.1760609e-37 7.7356102e-36]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009153604507446289
[1.6564228e-25 1.0000000e+00 4.4102882e-30 2.9868489e-23 4.9079380e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009142160415649414
[6.9352069e-23 1.0000000e+00 1.1769735e-27 5.3230959e-21 2.5421957e-17]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010182380676269531
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009303092956542969
[3.1381086e-21 1.0000000e+00 2.9200316e-22 7.1640267e-19 4.9073169e-14]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.012777090072631836


 92%|█████████▏| 229/250 [00:02<00:00, 93.24it/s]

tempo pred: 0.009637832641601562
[6.1499694e-17 1.0000000e+00 1.7403026e-13 3.0378884e-14 1.3413974e-09]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.011075258255004883
[3.1250730e-30 1.0000000e+00 7.2223115e-33 1.4180800e-23 3.1828941e-23]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009696245193481445
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010104894638061523
[2.9585671e-38 1.0000000e+00 0.0000000e+00 0.0000000e+00 9.6358863e-32]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010121822357177734
[1.0422431e-28 1.0000000e+00 1.4556497e-33 9.8146256e-24 4.3893678e-26]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010099649429321289
[2.3220082e-33 1.0000000e+00 1.3084844e-26 2.6061944e-27 5.1431187e-25]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.00909733772277832
[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 2.1045432e-38]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010220766067504883
[3.2139798e-17 1.0000000e+00 8.4524024e-19 1.5632656e-12 2.0040621e-13]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009238243103027344

 96%|█████████▌| 239/250 [00:02<00:00, 92.65it/s]


[0. 1. 0. 0. 0.]
curva
tempo pred: 0.011379241943359375
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009960651397705078
[0.000000e+00 1.000000e+00 0.000000e+00 0.000000e+00 7.776499e-36]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010644912719726562
[1.9384837e-17 1.0000000e+00 8.3284341e-21 2.3131883e-15 1.0453917e-15]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010121345520019531
[4.2770196e-09 8.8979053e-01 6.9476435e-08 1.1020907e-01 2.9395974e-07]
[0.   0.89 0.   0.11 0.  ]
curva
tempo pred: 0.009445905685424805
[1.0878553e-25 1.0000000e+00 0.0000000e+00 2.0235024e-38 1.8429630e-21]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010359764099121094
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009415864944458008
[2.674763e-36 1.000000e+00 0.000000e+00 7.697887e-32 3.610295e-32]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010485649108886719
[2.1973863e-32 1.0000000e+00 3.0332629e-36 1.8550471e-27 5.7083999e-24]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.009095430374145508
[0.0000000e+00 1.0000000e+00 

100%|██████████| 250/250 [00:03<00:00, 82.85it/s]

tempo pred: 0.00999140739440918
[3.0682447e-29 1.0000000e+00 4.4202596e-15 1.7531520e-25 2.6867904e-20]
[0. 1. 0. 0. 0.]
curva
tempo pred: 0.010381698608398438
[1.17005775e-26 1.00000000e+00 2.87230164e-32 9.00986821e-26
 8.11490428e-26]
[0. 1. 0. 0. 0.]
curva


In [15]:
output_names = ['dense_3/Softmax']
input_names = ['conv2d_1_input']

In [ ]:
1

In [10]:
tipos = ['cruzamento', 'curva', 'parada', 'reta', 'zigzag']
def predict(model_path,folder):
    # load tf graph
    tf_model,tf_input,tf_output = load_graph(model_path)
    print(tf_input,tf_output)
    # Create tensors for model input and output
    x = tf_model.get_tensor_by_name(tf_input)
    y = tf_model.get_tensor_by_name(tf_output) 
    num_outputs = y.shape.as_list()[0]
    
    fotos = (os.listdir(folder))
    predictions = np.zeros((len(fotos),len(tipos)))
    
    with tf.Session(graph=tf_model) as sess:
        for foto in tqdm(fotos):    
            tempo1 = time.time()
            y_out = sess.run(y, feed_dict={x: prepare_data_x(folder+foto)})
            print("tempo pred:",time.time()-tempo1)
            predictions = y_out[0]
            pred = np.around(predictions, decimals = 2, out = None) 
            print(tipos[np.argmax(pred)])
        #     return tipos[np.argmax(pred)],pred,input_data
#     return predictions

In [12]:
predict("/home/junior/Documents/seguidor_linha/modelo_9935.pb","/home/junior/Downloads/separado/parada/")


  0%|          | 0/250 [00:00<?, ?it/s]

prefix/conv2d_1_input:0 prefix/dense_3/Softmax:0



  0%|          | 1/250 [00:00<03:08,  1.32it/s]

tempo pred: 0.7553539276123047
parada



  1%|          | 2/250 [00:01<02:42,  1.53it/s]

tempo pred: 0.41387152671813965
parada



  1%|          | 3/250 [00:01<02:24,  1.71it/s]

tempo pred: 0.4164128303527832
parada



  2%|▏         | 4/250 [00:02<02:12,  1.86it/s]

tempo pred: 0.42806410789489746
parada



  2%|▏         | 5/250 [00:02<02:02,  2.00it/s]

tempo pred: 0.4134237766265869
parada



  2%|▏         | 6/250 [00:02<01:56,  2.09it/s]

tempo pred: 0.42081260681152344
parada



  3%|▎         | 7/250 [00:03<01:59,  2.03it/s]

tempo pred: 0.5254812240600586
parada



  3%|▎         | 8/250 [00:03<01:55,  2.10it/s]

tempo pred: 0.43256044387817383
parada



  4%|▎         | 9/250 [00:04<01:52,  2.14it/s]

tempo pred: 0.4427609443664551
parada



  4%|▍         | 10/250 [00:04<01:53,  2.12it/s]

tempo pred: 0.48052549362182617
parada



  4%|▍         | 11/250 [00:05<01:46,  2.23it/s]

tempo pred: 0.39119458198547363
parada



  5%|▍         | 12/250 [00:05<01:46,  2.24it/s]

tempo pred: 0.4359314441680908
parada



  5%|▌         | 13/250 [00:06<01:47,  2.21it/s]

tempo pred: 0.4667844772338867
parada


  5%|▌         | 13/250 [00:06<01:59,  1.99it/s]


KeyboardInterrupt: 

In [17]:
pwd

'/home/junior/Documents/carro2'